[build-system]
    requires = ["setuptools", "setuptools-scm"]
    build-backend = "setuptools.build_meta"

[project]
    name = "jux"
    description = "JUX is a jax-accelerated engine for Lux-2022."
    requires-python = ">=3.7, <3.11"
    license = { file = "LICENSE" }
    readme = "README.md"
    authors = [
        { name = "Qimai Li", email = "qimaili@chaocanshu.ai" },
        { name = "Yuhao Jiang", email = "yuhaojiang@chaocanshu.ai" },
    ]
    keywords = ["JAX", "LuxAI2022"]
    classifiers = [
        "Topic :: Games/Entertainment :: Real Time Strategy",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ]
    dependencies = [
        "luxai2022==1.1.3",
        "jax[cuda]~=0.3.25",
        "chex",
    ]
    dynamic = ["version"]

    [project.urls]
    repository = "https://gitlab.parametrix.cn/parametrix/challenge/jux"
    # TODO: add homepage url
    # TODO: add documentation url

    [project.optional-dependencies]
    torch = [
        "torch",
        "torchvision",
        "torchaudio",
    ]

    dev = [
        "toml",
        "pre-commit",
        "pytype",
        "tox",
        "tox-conda",
        "pytest",
        "pytest-cov",
        "isort",
        "autoflake",
        "yapf",
        "bump2version",
        "rich",
        "pandas",
    ]

[tool.setuptools.dynamic]
    version = { attr = "jux.__version__" }

[tool.yapf]
    column_limit = 120
    indent_width = 4

[tool.autoflake]
    imports = ["jax", "numpy", "chex"]
